### ISSUE TITLE
ck-ospell crashes when etc contains .zhfst files

### ISSUE THREAD

**Issue by albbas** [divvun/ck-ospell#3]
This is the error message:
repos/ck-ospell/server/app.js:22
  const locale = speller.locale()
                         ^

TypeError: speller.locale is not a function
    at langFiles.forEach.file (/home/boerre/repos/ck-ospell/server/app.js:22:26)
    at Array.forEach (native)
    at Object.<anonymous> (/home/boerre/repos/ck-ospell/server/app.js:19:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

This does not happen when etc is empty

**Comment by albbas** [comment]
Upping the hfst-ospell-js hash to the latest hfst-ospell-js commit seems to be part of solution, but then the hfst-ospell-js build stops.

**Comment by albbas** [comment]
This was fixed with commit [ eb617c7](https://github.com/divvun/hfst-ospell-js/commit/eb617c7bcb8e24fcd78e016b0ccbf7ce725c80d6) in [hfst-ospell-js](https://github.com/divvun/hfst-ospell-js)
